name: metadata-check

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch for push
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, developing ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    # The type of runner and python versions that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Install python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # Install dependencies
      - name: Install dependencies
        run: |
          pip install pytest
          pip install pandas

      # Run the checks
      - name: Checking metadata
        run:
          pytest
